[package]
name = "reactive-primitive"
version.workspace = true
edition.workspace = true
authors = ["storycraft <storycraft@pancake.sh>"]
license.workspace = true

[dependencies]
reactive.workspace = true
reactivity.workspace = true

bon = "3.3.2"
palette = "0.7.6"
