[workspace]
members = ["reactivity", "macro"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 or MIT"

[workspace.dependencies]
reactivity = { path = "./reactivity" }
reactivity-macro = { path = "./macro" }
