[package]
name = "example-app"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
reactive = { workspace = true }
reactivity = { workspace = true }

winit = "0.30.9"
glutin-winit = "0.5.0"
futures = { version = "0.3.31", default-features = false }
pin-project = "1.1.9"
