[package]
name = "example-app"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
reactive = { workspace = true }

async_ui_web = { git = "https://github.com/wishawa/async_ui" }
wasm-bindgen = "0.2.87" # 👈 For interfacing with JavaScript
futures-lite = "2.6.0"
